### ISSUE TITLE
feature/sgs-06-criacao-testes-unitarios-autenticacao

### ISSUE THREAD

**Issue by lucasrachid** [ifpr-paranavai/sistema_gerenciamento_servicos#6]

**Comment by Santyero** [comment]
### Analise Tecnica
Será necessario atribuir testes para a seguinte classe:

[DynamicModelPermissions](https://github.com/ifpr-paranavai/sistema_gerenciamento_servicos/blob/main/core/models/mixins.py)

**Comment by Santyero** [comment]
![Image](https://github.com/user-attachments/assets/3fd91512-3f9f-4e95-bd61-61d42bbe8664)

Calculando a Complexidade Ciclomática:

Nós (N): 7 (Start Test, Check User Permission, Prepare Data, Send POST Request, Check Response Status, Print Error Data, End Test)
Arestas (E): 8
Componentes Conectados (P): 1
Aplicando a fórmula de complexidade ciclomática: 
M=E−N+2P 
𝑀=8−7+2∗1=3
